### ISSUE TITLE
default aria2c location a bit weird?

### ISSUE THREAD

**Issue by ilcn** [nmbooker/aria2-tools#4]
ubuntu apt installs aria2c in /usr/local/bin, maybe say that in the readme? your default aria2c location in the script is in /opt something, and if the user doesn't know to check that it the script doesn't say anything.

**Comment by nmbooker** [comment]
Hi @ilcn I'm not using this at the moment, so if you're still interested could you please review pull request #5 to check if that update is sensible.

I have checked on Ubuntu 17.04 and aria2c is in /usr/bin by default so my patch reflects that:

```
$ sudo apt install aria2
$ which aria2c
/usr/bin/aria2c
```

**Comment by nmbooker** [comment]
Closed by #5
